FROM ghcr.io/osgeo/gdal:ubuntu-full-latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    libsqlite3-dev \
    zlib1g-dev \
    python3-pip \
    unzip \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf awscliv2.zip aws/

RUN pip3 install --no-cache-dir --break-system-packages pandas pyarrow

RUN mkdir /data

#COPY ./convert_to_pmtiles.sh /convert_to_pmtiles.sh
#RUN chmod +x /convert_to_pmtiles.sh
#ENTRYPOINT ["/convert_to_pmtiles.sh"]


#Notes
#docker build -t gdal .
#
#screen -S gdalrun
#
#docker run -it \
#  -e AWS_ACCESS_KEY_ID= \
#  -e AWS_SECRET_ACCESS_KEY= \
#  -e AWS_REGION=ap-southeast-2 \
#  -v $(pwd)/data/:/data \
#  gdal \
#  EEZ_land_union_v4_202410.pmtiles \
#  EEZ_land_union_v4_202410.parquet
#ctrl + a, then d
#screen -r gdalrun
#
#With entrypoint commented:
#docker run -it \
#  -e AWS_ACCESS_KEY_ID= \
#  -e AWS_SECRET_ACCESS_KEY= \
#  -e AWS_REGION=ap-southeast-2 \
#  -v $(pwd)/data/:/data \
#  gdal \
#  bash
#
#python3 -c "import pandas as pd; df = pd.read_parquet('/data/EEZ_land_union_v4_202410.parquet'); print(df.head())"
